### ISSUE TITLE
Usability: Colour Legend

### ISSUE THREAD

**Issue by valencik** [SMUCSM/SMUCSM.github.io#5]
Figuring out what colour means what requires a lot of scrolling at this point.
Any ideas to fix that?

**Comment by Frozenfire92** [comment]
I'm still playing with the idea of only showing the 5-10 nearest events

**Comment by valencik** [comment]
Maybe even just promoting the overview, as it might end up holding more general information later on.

If the overview gets sizable, it might make sense to have a quick link to the Upcoming Events section.

**Comment by Frozenfire92** [comment]
promoting the overview as in what type of events we do?
